{% set name = "dataclass-csv" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataclass-csv-{{ version }}.tar.gz
  sha256: 6a9207537ccdc3f381d50c3f5d053ce5a92ef0d61850f7a159e3f52eb79f0402

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pytest-runner
    - pip
  run:
    - python >=3.7
    # yes, distutils.util.strtobool is needed at runtime
    - setuptools

test:
  imports:
    - dataclass_csv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dfurtado/dataclass-csv
  summary: Map CSV data into dataclasses
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
